// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naovefbmlxpoeyymtpfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hb3ZlZmJtbHhwb2V5eW10cGZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjgxNTYsImV4cCI6MjA2MjgwNDE1Nn0.KtFQL3ovl1PiVBWHdYwLJ_cI7bM0OQX_Y2gdjcUH8N8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});